feat(keep): new PWA!
AliMD/alwatr pull request #1052
Opened 2023-04-17 20:34 UTC by njfamirm

2023-05-05 09:54 UTC, njfamirm commented on uniquely/keep-pwa/res/index.html
> +  <script type="module" src="config.js"></script>
.

2023-05-12 12:17 UTC, njfamirm commented on uniquely/keep-pwa/src/manager/submit-form-command-handler.ts
> +      // token: config.token,
.

2023-05-12 14:22 UTC, njfamirm commented on uniquely/keep-pwa/res/index.html
> +  <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#c24000" />
also for logo color

2023-05-13 11:47 UTC, AliMD commented on core/storage-engine/package.json
> +  "devDependencies": {
اجازه عوض کردن اینارو در این برنچ نداری مخصوصا که اشتباه هم کردی

2023-05-13 11:48 UTC, AliMD commented on cloud/alwatr/keep/env/keep-beta.env
تا زمانی که ورژن ۱ اش گرفته نشه نیاز به beta و canary نیست

2023-05-13 11:50 UTC, AliMD commented on cloud/alwatr/keep/compose.yml
> +  form-registration:
چه نیازی به فرم و استوریج بوده؟

2023-05-13 11:52 UTC, AliMD commented on uniquely/keep-pwa/res/index.html
> +  />
لطفا وقتی متوجه نکته‌ای نمیشی بپرس و حذفش نکن
برگردون به حالت قبل

2023-05-13 11:54 UTC, njfamirm commented on cloud/alwatr/keep/compose.yml
> +  form-registration:
فرم همکاری

2023-05-13 11:54 UTC, njfamirm commented on core/storage-engine/package.json
> +  "devDependencies": {
کامیت جدا زدم بعداً جداش کنیم

2023-05-13 11:54 UTC, njfamirm commented on cloud/alwatr/keep/env/keep-beta.env
اوکی، الان که باشه دیگه؟

2023-05-13 11:56 UTC, AliMD requested changes
متشکرم
زحمت کشیدی
چند تا کامنت نوشتم

اینو برای الان نمیگم ولی اکثر این صفحات و کدها مشترک هستش، کجا بره که همه از اون بگیرن

2023-05-13 11:57 UTC, njfamirm commented on uniquely/keep-pwa/res/index.html
> +  />
قبلا برای پرینت یک استایل رو اد کرده بودم فکر کردم اونه

2023-05-13 12:08 UTC, AliMD commented on uniquely/keep-pwa/res/index.html
> +  <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#c24000" />
این چیه که ریزالو نشده؟ نکتشو نفهمیدم؟

2023-05-13 12:10 UTC, AliMD commented on core/storage-engine/package.json
> +  "devDependencies": {
کلا ریبیس کن و حذفش کن
چرا باید devDependencie بشه؟؟

2023-05-13 12:11 UTC, AliMD commented on cloud/alwatr/keep/env/keep-beta.env
الان که ورژن ۱ کیپ نشده هنوز
ولی بشه هم مثل soffit لطفا

2023-05-13 14:51 UTC, AliMD commented
هر زمان dns ها اکی شد بگو مرج کنم

2023-06-14 13:22 UTC, merged