feat(com-pwa): `user-list` page
AliMD/alwatr pull request #1111
Opened 2023-05-02 17:23 UTC by mohammadhonarvar

2023-05-13 13:10 UTC, njfamirm commented on uniquely/com-pwa/src/manager/context-provider/sign-in.ts
> +    url: `${config.serverContext.api}/storage/user/${simpleHashNumber(phoneNumber)}-${token}`,
.

2023-05-13 14:58 UTC, njfamirm requested changes

2023-05-13 14:58 UTC, njfamirm commented on core/storage-client/src/storage-client.ts
>        name: string | undefined = this.config.name,
storage = this.config.name همین نمیشه؟

2023-05-13 14:58 UTC, njfamirm commented on core/storage-client/src/storage-client.ts
>    async keys(storage: string | undefined = this.config.name): Promise<Array<string>> {
همچنین اینجا

2023-05-13 14:58 UTC, njfamirm commented on uniquely/com-pwa/src/config.ts
> +    userOrderList: apiBaseUrl + 'publistore/auth/order-list',
publistore/auth/${token}/order-list ?
و بالاییش

2023-05-13 14:58 UTC, njfamirm commented on uniquely/com-pwa/src/manager/context-provider/order-storage.ts
> +        url: config.serverContext.userOrderList + '/' + user.id,
اینم باید بر اساس کانفیگ درست بشه

2023-05-13 14:58 UTC, njfamirm commented on uniquely/com-pwa/src/manager/context-provider/user-list-storage.ts
> +    config.fetchContextOptions,
url رو ندادین

2023-05-13 14:58 UTC, njfamirm commented on uniquely/com-pwa/src/manager/context-provider/user-list-storage.ts
> +          id: userId,
؟ باگ

2023-05-13 14:58 UTC, njfamirm commented on uniquely/com-pwa/src/ui/page/order.ts
> +        <img src="${config.serverContext.cdn + '/medium/' + product.image.id}" />
سوال:‌اینا نباید بره تو کانفیگ؟

2023-05-13 14:58 UTC, njfamirm commented on uniquely/com-pwa/src/ui/stuff/user-info-box.ts
> +        url: config.serverContext.userOrderList,
فکککککر میکنم userAuth هم باید باشه

2023-05-19 17:37 UTC, AliMD commented on uniquely/com-pwa/src/manager/context-provider/chat-storage.ts
این چیه یره؟!

2023-05-19 19:12 UTC, AliMD commented on uniquely/com-pwa/src/ui/stuff/user-info-box.ts
> +        url: config.serverContext.userOrderList,
فککککرررر نکن

2023-05-19 19:15 UTC, AliMD commented
@njfamirm 
ممنون برای ریویو ها
نکته بین شدی و این خیلی خوبه
در مورد API فقط باید بهت توضیح بدم که نیازی به token در url نیست و مدل api v2 تمام شده دیگه

2023-05-19 19:15 UTC, AliMD approved these changes

2023-05-19 19:16 UTC, merged

2023-05-19 19:19 UTC, njfamirm commented
> @njfamirm ممنون برای ریویو ها نکته بین شدی و این خیلی خوبه در مورد API فقط باید بهت توضیح بدم که نیازی به token در url نیست و مدل api v2 تمام شده دیگه

خواهش میکنم
خب خداروشکر