Fix build and lint workflows
AliMD/alwatr pull request #127
Opened 2022-03-28 16:36 UTC by ArmanA30

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes #(issue)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Open an issue for bug report or feature request and mention it to this PR.
- [ ] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [ ] All methods have proper description in `jsdocs` format with `@example` section.
- [ ] Docs have been added / updated (for bug fixes / features).
- [ ] I have performed a self-review of my own code.

## Other information

2022-03-28 16:36 UTC, ArmanA30 commented
@AliMD  OK?

2022-03-30 15:51 UTC, AliMD requested changes
Tnank you 👍🏻

2022-03-30 15:51 UTC, AliMD commented on package.json
> +    "build": "npm-run-all --sequential build:ts build:es",
ما اینجا build:es نداریم
خودت ببین تو اسم اسکریپت ها

2022-03-31 12:33 UTC, ArmanA30 commented on package.json
> +    "build": "npm-run-all --sequential build:ts build:es",
خودم شک کردم 
ولی چون گفته بودید بر اساس alwatr-pwa این تغییرات انجام بشه...!
 الان alwatr-pwa هم همین اشکال رو داره...؟
 https://github.com/AliMD/alwatr-pwa/blob/next/package.json

2022-04-01 11:16 UTC, AliMD commented on package.json
> +    "build": "npm-run-all --sequential build:ts build:es",
خودم انجام میدم

2022-04-02 00:27 UTC, AliMD approved these changes

2022-04-02 00:27 UTC, merged