feat(font): add sahel font
AliMD/alwatr pull request #132
Opened 2022-04-12 17:32 UTC by sahbaee

2022-04-15 18:56 UTC, AliMD requested changes
Thanks

2022-04-15 18:56 UTC, AliMD commented on package/font/font.css
> +  font-weight: 400;
recheck plz

2022-04-15 18:56 UTC, AliMD commented on package/font/font.css
> +  font-weight: 400 900;
300

2022-04-17 07:01 UTC, sahbaee commented on package/font/font.css
> +  font-weight: 400;
checked ok bood

2022-04-19 16:19 UTC, AliMD commented on package/font/font.css
> +  font-weight: 400 900;
این همچنان ۴۰۰ هستش که!
درست کن مرج کنم دیگه

2022-04-19 17:00 UTC, merged

2022-04-19 17:00 UTC, AliMD commented
تو یک پول جدید لطفا اصلاح کن