Feat/icon
AliMD/alwatr pull request #133
Opened 2022-04-15 19:02 UTC by MM25Zamanian

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes #(issue)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Open an issue for bug report or feature request and mention it to this PR.
- [x] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [x] All methods have proper description in `jsdocs` format with `@example` section.
- [x] Docs have been added / updated (for bug fixes / features).
- [x] I have performed a self-review of my own code.

## Other information

2022-04-16 04:31 UTC, AliMD requested changes
نکته زیاد داره
ولی همینکه شروع شد ممنون

2022-04-16 04:31 UTC, AliMD commented on package/icon/README.md
> +# @alwatr/fetch
!!!

2022-04-16 04:31 UTC, AliMD commented on package/icon/package.json
> +  "description": "Premium icons for AlWatr.",
Premium!!

2022-04-16 04:31 UTC, AliMD commented on package/icon/src/icon.ts
> +  @state() private isVisible = false;
این چیه؟!!

2022-04-16 04:31 UTC, AliMD commented on package/icon/src/icon.ts
> +  ): void {
حتمی باید
super.willUpdate
رو اجرا کنی
از طرفی استفاده از اینو دوست ندارم

2022-04-16 20:12 UTC, MM25Zamanian commented on package/icon/package.json
> +  "description": "Premium icons for AlWatr.",
باید یه توضیحات واسش بنویسین
من در همین حد بلد بودم و از روی آیونیک اسکی رفتم

2022-04-16 20:14 UTC, MM25Zamanian commented on package/icon/src/icon.ts
> +  @state() private isVisible = false;
اگر به هر دلیلی آیکون درست کار نکنه کلا هیچی رو نمایش نمیده
و اینکه الان کاربرد خاصی نداره با اضافه شدن پیچیدگی های بیشتر این بهترین روش ممکن هستش

2022-04-16 20:15 UTC, MM25Zamanian commented on package/icon/src/icon.ts
> +  ): void {
حقیقتا با خوندم داکیومنتش به این نتیجه رسیدم
ولی استفاده از `update` رو هم میتونم جایگزین کنم

2022-04-17 19:22 UTC, asmanp2012 commented on package/icon/package.json
> +  "description": "Premium icons for AlWatr.",
محمد مهدی متنش و درست با میون کارای دیگت بفرست بالا کلمه Premium باید حذف بشه

2022-04-17 19:24 UTC, asmanp2012 commented on package/icon/src/icon.ts
> +  ): void {
محمد مهدی super.willupdate رو که میتونی بزاری اونو بزار

2022-04-17 19:30 UTC, asmanp2012 requested changes

2022-04-17 19:30 UTC, asmanp2012 commented on package/icon/src/core.ts
> +import {alwatrRegisteredList, createLogger} from '@alwatr/logger';
با وجود این فایل به کل مشکل دارم  @AliMD  آیا توی هر کدوم از فایل ها اگر یک کلاس لاگر ایجاد کنه مشکلی پیش میادش ؟؟

اون قسمت دومم که برای ریجیستر کردن هستش که پایین همین کامنت گذاشتمش محمد مهدی @MM25Zamanian احساس میکنم فقط توی یکی از فایل ها بزاری کافیه اونم فایل اصلی که المنت رو تعریف کردی:

```typescript
alwatrRegisteredList.push({
  name: '@alwatr/icon',
  version: '{{ALWATR_VERSION}}',
});
```

2022-07-20 06:17 UTC, AliMD commented
کی فرصت داری بیای حضوری باهم بنویسیم؟

2022-07-20 06:17 UTC, closed without merging