fix(i18n): issue #154
AliMD/alwatr pull request #155
Opened 2022-05-16 17:22 UTC by MM25Zamanian

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes #(issue)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Open an issue for bug report or feature request and mention it to this PR.
- [x] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [x] All methods have proper description in `jsdocs` format with `@example` section.
- [x] Docs have been added / updated (for bug fixes / features).
- [x] I have performed a self-review of my own code.

2022-05-17 14:34 UTC, AliMD requested changes
اینکه کلا چک نکنه که نمیشه! باعث میشه تکراری لود بشه
بهترین راه برای اینکه بفهمیم لوکال واقعا فرق کرده چیه؟
تازه ممکنه ریسورس درست لود نشده باشه پس باید با خود ریسورس چک بشه! یا به قول شما اصلا چک نشه راحت تره
باید حرف بزنیم

2022-05-17 14:36 UTC, AliMD commented
اینکه fetch امکان catch داشته باشه فکر کنم از همه بهتر باشه
یا حتی اینکه خود این تابع امکان کش داشته باشه، مشکل کامل حل میشه

2022-05-23 20:28 UTC, MM25Zamanian commented
خب من چه کنم الان ؟؟؟

2022-07-20 06:52 UTC, AliMD commented
fixed in #165

2022-07-20 06:52 UTC, closed without merging