docs(nano-server): `jsdocs` example
AliMD/alwatr pull request #177
Opened 2022-08-01 14:01 UTC by MM25Zamanian

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [x] All methods have proper description in `jsdocs` format with `@example` section.
- [x] Docs have been added / updated (for bug fixes / features).
- [x] I have performed a self-review of my own code.

2022-08-02 12:32 UTC, AliMD requested changes
Thank you
All docs need examples

2022-08-02 22:39 UTC, MM25Zamanian commented on packages/core/nano-server/src/nano-server.ts
> +   * request body
What do you think is the best explanation?

2022-08-02 22:39 UTC, MM25Zamanian commented on packages/core/nano-server/src/nano-server.ts
> +   * Creating a route to receive requests on the server
What do you think is the best explanation?

2022-08-03 23:38 UTC, AliMD requested changes
چرا احساس میکنم از این کار خوشت نمیاد
گفتم اونجا نشستی نیم ساعته اینارو بنویسم 
فکر نمیکردم به چند روز بکشه!

2022-08-03 23:38 UTC, AliMD commented on packages/core/nano-server/src/nano-server.ts
> +   * Creating a route to receive requests on the server
منظورم اینکه که حالت all رو هم توضیح بده

2022-08-03 23:38 UTC, AliMD commented on packages/core/nano-server/src/nano-server.ts
> +   * extracted auth token from header connection
اینارو که هیچ کدوم درست نکردی چرا ریزالو زدی؟

2022-08-03 23:38 UTC, AliMD commented on packages/core/nano-server/src/nano-server.ts
> +   * @returns json or null
اینم حل نشده!

2022-08-05 18:31 UTC, AliMD commented
@MM25Zamanian 
اگر نمیرسی یا حال نمیکنه بگو لطفا

2022-08-05 21:41 UTC, MM25Zamanian commented
> @MM25Zamanian اگر نمیرسی یا حال نمیکنه بگو لطفا

نمیرسم

2022-08-06 20:31 UTC, closed without merging