Add nano-server jsdoc
AliMD/alwatr pull request #184
Opened 2022-08-07 11:40 UTC by njfamirm

## Description

add jsdoc for nano-server

Fixes #(issue)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Open an issue for a bug report or feature request and mention it to this PR.
- [x] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [x] All methods have proper description in `jsdocs` format with `@example` section.
- [x] Docs have been added / updated (for bug fixes / features).
- [x] I have performed a self-review of my own code.

2022-08-07 12:12 UTC, njfamirm commented on packages/core/nano-server/src/nano-server.ts
> + * Connection...?
?

2022-08-07 12:14 UTC, njfamirm commented
تایپا رو نمی دونم!

2022-08-09 12:02 UTC, njfamirm commented
> تایپا رو نمی دونم!

با توجه به وجود تایپا در ts ایا اصلا لازمه تایپ رو توی jsdoc بزاریم؟

2022-08-09 12:15 UTC, njfamirm commented
> > تایپا رو نمی دونم!
> 
> با توجه به وجود تایپا در ts ایا اصلا لازمه تایپ رو توی jsdoc بزاریم؟

https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#type

2022-08-12 21:22 UTC, MM25Zamanian requested changes

2022-08-12 21:22 UTC, MM25Zamanian commented on packages/core/nano-server/src/nano-server.ts
> +   * @param {Partial<Config>=} config Server config.
WTF?

2022-08-12 21:22 UTC, MM25Zamanian commented on packages/core/nano-server/src/nano-server.ts
> +   * Starts the HTTP server listening for connections.
@AliMD این مدل بهتره یا اینکه بگی این مثلا شورت کات فلان دستوره؟

2022-08-12 21:22 UTC, MM25Zamanian commented on packages/core/nano-server/src/nano-server.ts
> +   * @param {(connection: AlwatrConnection) => void} middleware Request handler.
کلا بخاطر تایپ اسکریپتی بودن پکیج نیاز به تعریف پارامتر ها در jsdoc نداری

2022-08-12 21:22 UTC, MM25Zamanian commented on packages/core/nano-server/src/nano-server.ts
> +   * @param {ReplyContent} content Reply content.
WTF?

2022-08-13 00:12 UTC, AliMD commented
کلا @param ها اضافی هستش مگر توضیحی لازم داشته باشه
و همه Example لازم دارن

2022-08-13 00:13 UTC, AliMD commented on packages/core/nano-server/src/nano-server.ts
> +   * Starts the HTTP server listening for connections.
این جالبتره

2022-08-13 00:51 UTC, njfamirm commented on packages/core/nano-server/src/nano-server.ts
> +   * @param {(connection: AlwatrConnection) => void} middleware Request handler.
خودم بهش فکر کردم؛ اما خب با خودم گفتم پس چرا ts گذاشته این آپشن رو در jsdocش؟

2022-08-13 01:20 UTC, njfamirm commented on packages/core/nano-server/src/nano-server.ts
> + * Connection...?
@AliMD

2022-08-13 01:22 UTC, njfamirm commented on packages/core/nano-server/src/nano-server.ts
> +   * @param {Partial<Config>=} config Server config.
اولی اسم پارامتره

2022-08-13 01:24 UTC, njfamirm commented
> کلا @param ها اضافی هستش مگر توضیحی لازم داشته باشه و همه Example لازم دارن

اوکی
الان که همه example دارن...

2022-08-13 10:28 UTC, AliMD commented
پس لطفا کانفلیکت رو بر طرف کن که زودتر مرج کنم بعد کامل ترش میکنیم
درضمن همین خروجی رو باید ببریم رو ریدمی
یا تو همین پول انجام بشه یا یک تسک بزن برای بعد

2022-08-13 12:09 UTC, njfamirm commented
به ریدمی اضافه شد
اماده اس

فقط یک روز باید به یک فرمت برای کل داکیومنت ها برسیم و همه رو اپدیت کنیم
به تسک اضافه بشه؟

2022-08-13 14:24 UTC, AliMD approved these changes
👍🏻

2022-08-13 14:26 UTC, merged