refactor(traefik-proxy): config to latest version
AliMD/alwatr pull request #200
Opened 2022-08-17 07:25 UTC by MM25Zamanian

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Open an issue for bug report or feature request and mention it to this PR.
- [x] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [x] All methods have proper description in `jsdocs` format with `@example` section.
- [x] Docs have been added / updated (for bug fixes / features).
- [x] I have performed a self-review of my own code.

2022-08-17 11:50 UTC, njfamirm commented
<img width="697" alt="Screen Shot 1401-05-26 at 16 19 52" src="https://user-images.githubusercontent.com/83071310/185111480-1bd48358-d770-4b97-8d32-d3db3e328729.png">


> A Compose implementation SHOULD NOT use this version to select an exact schema to validate the Compose file, but prefer the most recent schema at the time it has been designed.

https://docs.docker.com/compose/compose-file/#version-top-level-element

2022-08-17 11:51 UTC, njfamirm commented
عجیبه!

2022-08-18 01:12 UTC, AliMD commented
خودم رفتم کامل خوندم
کلا اینم از داکر گرفتن 😆 
رفته اینجا https://compose-spec.io/
و عجب cli های خوبی برش نوشتن
کلا باید از داکر بکشیم بیرون
لطفا تغییراتی که در #203 دادم رو ببین و رو همه اعمال کن
از اسم فایل تا مدل نتورک تا فایل _up که با دستور جدید داخل داکر کار میکنه
فقط‌ اولیت بده لطفا

2022-08-18 01:16 UTC, AliMD requested changes
خودم رفتم کامل خوندم
کلا اینم از داکر گرفتن 😆
رفته اینجا https://compose-spec.io/
و عجب cli های خوبی برش نوشتن
کلا باید از داکر بکشیم بیرون
لطفا تغییراتی که در https://github.com/AliMD/alwatr/pull/203 دادم رو ببین و رو همه اعمال کن
از اسم فایل تا مدل نتورک تا فایل _up که با دستور جدید داخل داکر کار میکنه
فقط‌ اولیت بده لطفا

2022-08-19 07:07 UTC, closed without merging