New Package: Alwatr Accelerated Nginx Container
AliMD/alwatr pull request #221
Opened 2022-08-22 13:33 UTC by AliMD

2022-08-24 18:19 UTC, AliMD commented on packages/container/nginx/conf/entrypoint.d/10-envsubst-on-templates.sh
> +# vim:sw=2:ts=2:sts=2:et
کانفیک vim بوده از قبل که مونده

2022-08-28 12:10 UTC, adltalab commented on packages/container/nginx/Dockerfile
> +# Default enviroment for nginx template
spell check:
enviro`n`ment

2022-08-28 15:01 UTC, njfamirm commented on packages/container/nginx/Dockerfile
> +# Default enviroment for nginx template
please request change!

2022-08-29 06:32 UTC, adltalab requested changes
spell check:
enviro`n`ment

2022-09-01 19:09 UTC, adltalab commented
```suggestion
# Default environment for nginx template
```

2022-09-01 19:24 UTC, adltalab commented on packages/container/nginx/Dockerfile
> +# Default enviroment for nginx template
```suggestion
# Default environment for nginx template
```

2022-09-01 19:25 UTC, adltalab requested changes

2022-09-01 19:25 UTC, adltalab commented on packages/container/nginx/Dockerfile
> +# Default enviroment for nginx template
```suggestion
# Default environment for nginx template
```

2022-09-04 23:01 UTC, merged