Fix(core/router/readme) : spelling mistake
AliMD/alwatr pull request #230
Opened 2022-08-25 10:46 UTC by amiresp

2022-08-26 09:19 UTC, amiresp commented
@njfamirm & @AliMD 
thanks for review 🚀 
please check [this](https://github.com/AliMD/alwatr/pull/230/commits/b872b482ae362a8f5ea23dfe69e376fe7e10b0c8).

2022-08-27 21:30 UTC, AliMD requested changes

2022-08-27 21:30 UTC, AliMD commented on packages/core/logger/README.md
> +  window.localStorage?.setItem('ALWATR_LOG', '*');
چرا اینو اضافه کردی؟!
این اشتباه هستش و بخش بعدی درسته

2022-08-27 21:30 UTC, AliMD commented on packages/core/router/README.md
> +### Route object
مرسی 👍🏻 
لطفا یک پول دیگه بده و فقط اینو دست کن

2022-08-27 21:32 UTC, AliMD commented
حالا که داری پول جددی میدی یک جا دیگه هم در توضیحات `ALWATR_LOG`اومده که باید به `ALWATR_DEBUG` تقییر کنه

2022-08-28 06:56 UTC, amiresp commented
چشم 
انجام میشه

2022-08-28 06:56 UTC, closed without merging

2022-08-28 07:03 UTC, amiresp commented
> 

این موردو پیدا نمیکنم ، حداقل تو readme لاگر نیست