Improve documention
AliMD/alwatr pull request #254
Opened 2022-08-31 18:15 UTC by njfamirm

2022-08-31 18:16 UTC, njfamirm commented
https://github.com/AliMD/alwatr/pull/152/

@alimd لطفا تغییراتی که لازمه رو بگین از این بردارم

2022-09-18 21:56 UTC, AliMD commented
?!
این چیه داستانش
تمامش کنیم

2022-09-19 05:41 UTC, njfamirm commented
یکسری خورده کاریا
و همچنین اونایی که از #153 خوب بود رو اینجا منتقل میکنم

2022-09-19 05:41 UTC, njfamirm commented
> #152
> 
> @AliMD لطفا تغییراتی که لازمه رو بگین از این بردارم

بگین همین رو

2022-09-19 05:54 UTC, AliMD commented
یکی تنظیمات eslint

قانون operator-linebreak باید این باشه

`"after", { "overrides": { "?": "before", ":": "before" } }
`
این مقدار پیشفرض هستش آیا واقعا لازمه نوشته بشه؟

2022-09-19 05:57 UTC, AliMD commented
یکی تنظیمات prettier که جدا بررسیش کنیم
خیلی از چیزهایی که میخوایم در این لامصب اصلا تنظیم نداره
شاید اگر بیاد تو eslint بشه با تنظیمات eslint خودمون override کنیم و دیگه دو بار اعمال نشه
و اگر خیلی مهم نیست مدل prettier رو بپذیریم 💩

2022-09-19 08:05 UTC, adltalab commented on packages/core/logger/README.md
>  Please remember to **reload** the window after changing the debug mode.
```suggestion
Many of the methods in the logger are no-ops when the debug mode is off in the browser.
Please remember to **reload** the window after changing the debug mode.
```

2022-09-19 12:53 UTC, AliMD commented
یک موضوع مهم دو فایل برای prettierignore و eslintignore میخوایم و باید حالت فعلی که از gitignpre استفاده میکنه تغییر کنه

2022-09-23 11:53 UTC, AliMD requested changes

2022-09-23 11:53 UTC, AliMD commented on packages/core/storage/src/storage.ts
> +import type {DocumentObject, DocumentListStorage, AlwatrStorageConfig} from './type.js';
تو import type که .js لازم نداره!

2022-09-23 11:53 UTC, AliMD commented on packages/core/signal/src/signal.ts
> +    // eslint-disable-next-line @typescript-eslint/no-use-before-define
این چیه؟

2022-09-23 11:53 UTC, AliMD commented on .eslintrc.json
> +    "operator-linebreak": ["error", "after", {"overrides": {"?": "before", ":": "before"}}],
این مگه default نبود؟

2022-09-24 10:57 UTC, merged