feat(alwatr-icon): improve
AliMD/alwatr pull request #343
Opened 2022-10-22 21:30 UTC by MM25Zamanian

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes #(issue)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Open an issue for bug report or feature request and mention it to this PR.
- [ ] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [ ] All methods have proper description in `jsdocs` format with `@example` section.
- [ ] Docs have been added / updated (for bug fixes / features).
- [ ] I have performed a self-review of my own code.

## Other information

2022-10-22 21:31 UTC, MM25Zamanian commented
لطفا سریع تر آیکون پک رو تایین کنید

2022-10-22 21:39 UTC, MM25Zamanian commented
```sh
alwatr/
├─ ui/
│  ├─ alwatr-icon/
│  ├─ alwatr-grid/
│  ├─ .../
├─ core/
├─ .../
```
Or
```sh
```

2022-10-28 08:27 UTC, AliMD requested changes

2022-10-28 08:27 UTC, AliMD commented on packages/ui/icon/package.json
> +  "description": "Premium icons for Ionic. ",
WTF! ionic?!!

2022-10-28 08:27 UTC, AliMD commented on packages/ui/icon/package.json
> +  "author": "MohammadMahdi Zamanian <mm25zamanian@gmail.com> (https://mm25zamanian.ir)",
وقتی در یک پروژه مشارک میکنی اسم خودت رو در contributors باید اضافی کنی نه author

2022-10-28 08:27 UTC, AliMD commented on packages/ui/icon/src/icon.ts
> +export class AlwatrIcon extends AlwatrElement {
صحبت های دیشب فراموش شد؟!

2022-10-28 08:27 UTC, AliMD commented on packages/ui/icon/tsconfig.json
> +    // { "path": "../x" },
element

2022-10-28 08:27 UTC, AliMD commented on packages/ui/icon/package.json
> +  "dependencies": {
lit

2022-10-28 08:27 UTC, AliMD commented on tsconfig.json
> +    {"path": "./packages/core/element"},
ooops! tnx

2022-10-31 12:00 UTC, AliMD requested changes

2022-10-31 12:00 UTC, AliMD commented on packages/ui/icon/package.json
> +{
add private

2022-10-31 12:00 UTC, AliMD commented on packages/ui/icon/src/icon.ts
> +      <svg width="512" height="512" viewBox="0 0 512 512">
replace with new svg

2022-10-31 12:20 UTC, merged