fix: Import error in webpack
AliMD/alwatr pull request #350
Opened 2022-10-26 19:49 UTC by asmanp2012

## Description

Add mime type in imports

Fixes #324

## PR Checklist

Please check if your PR fulfills the following requirements:

- [*] Open an issue for bug report or feature request and mention it to this PR.
- [*] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [ ] All methods have proper description in `jsdocs` format with `@example` section.
- [ ] Docs have been added / updated (for bug fixes / features).
- [ ] I have performed a self-review of my own code.

## Other information

2022-10-28 08:17 UTC, AliMD requested changes
الان تمام پروژه همینا بود فقط یا نمونه ساختی؟
از طرفی ممکنه import type ها هم لازم داشته باشه؟

2022-10-28 08:17 UTC, AliMD commented on packages/core/element/src/element.ts
> +import type {Constructor} from './type.js';
ایمپورت تایپ ها که js نمیخواد!

2022-10-28 14:54 UTC, asmanp2012 commented on packages/core/element/src/element.ts
> +import type {Constructor} from './type.js';
> الان تمام پروژه همینا بود فقط یا نمونه ساختی؟ از طرفی ممکنه import type ها هم لازم داشته باشه؟

همه پکیج هایی که داخل پوشه package بود رو اصلاح کردم فکر نمیکنم چیزی اونجا باقی مونده باشه
حالا که داریم انجام میدیم همه یک شکل بشن دیگه به خاطر اون فایل های تایپی که ساخته برای جی اس ها هم ایمپورت تایپ ها کار میکنه لزومش رو چک نکردم

2022-10-31 10:59 UTC, AliMD commented on packages/core/element/src/element.ts
> +import type {Constructor} from './type.js';
> import type only imports declarations to be used for type annotations and declarations.

این اشتباه هستش
یعنی اگر تایپ میزاری باید .d.ts باشه
به نظرم یا حذف بشه یا d.ts. باشه

2022-10-31 11:02 UTC, AliMD commented on packages/core/element/src/element.ts
> +import type {Constructor} from './type.js';
@MM25Zamanian Check lit

2022-10-31 11:03 UTC, AliMD approved these changes

2022-10-31 11:03 UTC, merged

2022-10-31 21:28 UTC, asmanp2012 commented on packages/core/element/src/element.ts
> +import type {Constructor} from './type.js';
> https://github.com/lit/lit/blob/039063aaab4e9507f42cdddd4ef737cf10839cbb/packages/localize-tools/src/formatters/index.ts#L12

چه عجیییب فکر نمیکردم لیت هم همین کار رو انجام بده