Feat/alwatr font
AliMD/alwatr pull request #353
Opened 2022-10-31 13:06 UTC by MM25Zamanian

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes #(issue)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Open an issue for bug report or feature request and mention it to this PR.
- [ ] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [ ] All methods have proper description in `jsdocs` format with `@example` section.
- [ ] Docs have been added / updated (for bug fixes / features).
- [ ] I have performed a self-review of my own code.

## Other information

2022-10-31 13:24 UTC, MM25Zamanian commented on packages/ui/font/package.json
>    "main": "font.css",
`vazirmatn.css`

2022-11-01 15:13 UTC, AliMD requested changes

2022-11-01 15:13 UTC, AliMD commented on packages/ui/font/README.md
>  [Demo](https://jsbin.com/zucajut/1/edit?html,output)
remove `/1/`

2022-11-01 15:29 UTC, AliMD approved these changes

2022-11-01 15:29 UTC, merged