fix(nano-server): handle preflight request
AliMD/alwatr pull request #433
Opened 2022-11-26 10:22 UTC by njfamirm

2022-11-26 10:22 UTC, njfamirm commented
https://github.com/AliMD/alwatr/pull/433

2022-11-26 11:11 UTC, AliMD requested changes
این باعث میشه دیگه طرف نتونه route option تعریف کنه
از طرفی فقط API به این موضوع نیاز داره آیا برای همه بزاریم واقعا؟!

2022-11-27 11:01 UTC, AliMD approved these changes

2022-11-27 11:35 UTC, AliMD approved these changes

2022-11-27 11:35 UTC, merged