fix(ff-pwa): ui issue
AliMD/alwatr pull request #524
Opened 2022-12-19 17:22 UTC by MM25Zamanian

## PR Checklist

- [ ] Open an issue for bug report or feature request and mention it to this PR.
- [ ] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [ ] All methods have proper description in `jsdocs` format with `@example` section.
- [ ] Docs have been added / updated (for bug fixes / features).
- [ ] I have performed a self-review of my own code.

2022-12-20 04:50 UTC, njfamirm requested changes

2022-12-20 04:50 UTC, njfamirm commented on uniquely/flight-finder-pwa/src/type.ts
> +export type jobMeta = {formatVersion: 4; lastAutoId: 18; lastUpdated: 1671454823773; reversion: 5742};
?

2022-12-20 04:50 UTC, njfamirm commented on uniquely/flight-finder-pwa/src/type.ts
> +export type jobMeta = {formatVersion: 4; lastAutoId: 18; lastUpdated: 1671454823773; reversion: 5742};
از فتچ بگیر

2022-12-20 12:50 UTC, njfamirm commented on uniquely/flight-finder-pwa/src/util/human-time.ts
> +}
خب یکم تغییر میخواد
انجام بده (یا بدم)
البته یکی فقط فاصله رو محاسبه کنه به ms
یکی هم کانورت کنه

2022-12-20 16:29 UTC, AliMD commented on uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
> +      const relativeTimeObject = getHumanTime(now - (jobList.meta?.lastUpdated ?? now));
اولا lastUpdated که همیشه هست ولی اگر هم قراره آپشنال باشه چرا باید وقتی میدونی همیشه صفر میشه نازم به getHumanTime پاسش بدی؟!

2022-12-20 16:36 UTC, AliMD commented on uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
> +  static relativeTimeFormatter = new Intl.RelativeTimeFormat('fa-IR', {style: 'narrow'});
هیچ نیازی به این نیست!

2022-12-20 16:37 UTC, AliMD commented on uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
> +      this.__relativeTime = PageFlightFinder.relativeTimeFormatter.format(
هیچ نیازی به این نیست!

2022-12-20 16:37 UTC, AliMD commented on uniquely/flight-finder-pwa/src/util/human-time.ts
> +}
هیچ نیازی به این نیست!

2022-12-20 16:39 UTC, AliMD commented on uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
> +    PageFlightFinder.jobDataSignal.addListener((jobList) => {
با اسم متغیر و همچنین سیگنال مشکل دارم
و کلا با ینکه دیتا سرور رو عوض میکنه میکنی مشکل دارم!

2022-12-20 16:39 UTC, AliMD commented on uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
> +          <ion-card-subtitle>${this.__relativeTime}</ion-card-subtitle>
همون حالت قبل باید باشه فقط عدد خیلی ساده محسابه بشه

2022-12-20 16:40 UTC, AliMD commented on uniquely/flight-finder-pwa/src/director/job-data.ts
> +import type {Job, jobMeta} from '../type.js';
متا رو کلا از fetch بگیر

2022-12-20 16:41 UTC, AliMD commented on uniquely/flight-finder-pwa/src/director/job-data.ts
> +export const jobDataSignal = new SignalInterface('job-data');
jobStorageSignal = new SignalInterface('job-storage');

2022-12-20 16:42 UTC, AliMD commented on uniquely/flight-finder-pwa/src/director/job-data.ts
>      const response = await fetch({
تابع fetch همه جا کلا با serviceRequest باز نویسی بشه

2022-12-20 17:17 UTC, AliMD commented on uniquely/flight-finder-pwa/src/director/job-data.ts
> +        _dispatchJobList(response.clone());
Fixed #529

2022-12-20 17:19 UTC, AliMD commented on uniquely/flight-finder-pwa/src/type.ts
> +    readonly 'job-data': AlwatrServiceResponse<Record<string, Job>, jobMeta> & {ok: true};
از ResponseSuccessWithMeta باید استفاده کنی

2022-12-20 17:20 UTC, AliMD commented on uniquely/flight-finder-pwa/src/type.ts
> +export type jobMeta = {formatVersion: 4; lastAutoId: 18; lastUpdated: 1671454823773; reversion: 5742};
کلا از خود fetch بیاد

2022-12-20 17:20 UTC, AliMD commented on uniquely/flight-finder-pwa/src/type.ts
> +export type jobMeta = {formatVersion: 4; lastAutoId: 18; lastUpdated: 1671454823773; reversion: 5742};
حالا من اصلا نمیدونم چرا متا لازم داری؟!
کلا تایمی کی نشون میده مگه تایم ریفرش نیست؟ خوب موقع اومدن باید ست بشه دیگه

2022-12-20 17:22 UTC, AliMD commented on yarn.lock
> +"@esbuild/android-arm64@0.16.9":
چرا باید تو این برنچ yarn آپگریت بشه؟

2022-12-20 17:42 UTC, AliMD commented
کامیت `37c8a8b` روح حذف کردم
لطفا reset کنید
```
git fetch
git reset --hard origin/feat/ff-pwa
```

2022-12-20 19:18 UTC, AliMD commented
@MM25Zamanian 
من دارم رو این برنچ کار میکنم اگر خواستی شروع کنی حتما خبر بده پوش کنم

2022-12-21 06:59 UTC, njfamirm commented on uniquely/flight-finder-pwa/src/type.ts
> +export type jobMeta = {formatVersion: 4; lastAutoId: 18; lastUpdated: 1671454823773; reversion: 5742};
تایم رفرش که مهم نیست
بنظرم تایم کرالر مهمه

2022-12-21 09:58 UTC, AliMD commented on uniquely/flight-finder-pwa/src/director/job-data.ts
> +export const jobDataSignal = new SignalInterface('job-data');
بله

2022-12-21 10:21 UTC, AliMD commented on uniquely/flight-finder-pwa/src/component/page-flight-finder.ts
> +      span#timer{
!

2022-12-21 10:40 UTC, AliMD approved these changes

2022-12-21 10:43 UTC, njfamirm approved these changes

2022-12-21 10:43 UTC, merged