fix(flight-crawler): min&max hour in make message
AliMD/alwatr pull request #555
Opened 2022-12-22 13:53 UTC by njfamirm

2022-12-22 18:38 UTC, AliMD commented on services/flight-crawler/src/crawl.ts
> +    فیلتر زمانی: ${job.detail.maxPrice ? `بین ${job.detail.minHour} و ${job.detail.maxPrice}` : 'ندارد' }
maxPrice?!

2022-12-22 18:41 UTC, njfamirm commented on services/flight-crawler/src/crawl.ts
> +    فیلتر زمانی: ${job.detail.maxPrice ? `بین ${job.detail.minHour} و ${job.detail.maxPrice}` : 'ندارد' }
اوه!!

2022-12-22 18:43 UTC, AliMD commented on services/flight-crawler/src/crawl.ts
> +    فیلتر زمانی: ${job.detail.maxPrice ? `بین ${job.detail.minHour} و ${job.detail.maxPrice}` : 'ندارد' }
بنویسی از ساعت فلان تا فلان یا هیچی بهتره

2022-12-22 18:43 UTC, AliMD requested changes
!

2022-12-22 18:44 UTC, njfamirm commented on services/flight-crawler/src/crawl.ts
> +    فیلتر زمانی: ${job.detail.maxPrice ? `بین ${job.detail.minHour} و ${job.detail.maxPrice}` : 'ندارد' }
اوکی

2022-12-23 12:09 UTC, AliMD requested changes
تو کامنت قبلی نوشته بودم اگر بنویسی از ساعت فلان تا فلان یا هیچی بهتره
و هردومتغییر رو چک کن

2022-12-24 07:39 UTC, njfamirm commented
review again please

2022-12-24 15:07 UTC, AliMD requested changes
نوشته بودم از ساعت فلان تا فلان
کمه ساعت دوم در متن اضافیه

2022-12-25 09:10 UTC, njfamirm commented
review again, please @AliMD

2022-12-25 17:08 UTC, AliMD approved these changes
🎉 🎉 🎉 🎉

2022-12-25 17:09 UTC, merged