feat(type): add storage, service, chat types
AliMD/alwatr pull request #589
Opened 2022-12-28 19:05 UTC by njfamirm

2022-12-28 19:37 UTC, njfamirm commented
wtf!

2022-12-29 07:52 UTC, njfamirm commented on core/type/src/type.ts
> +// FIXME:
کجا برن این دو تا تایپ؟

2022-12-29 07:52 UTC, njfamirm commented on ui/demo-pwa/src/director/comment-add.ts
> +commentDocumentStorageSignal.request(null);
remove

2022-12-29 07:52 UTC, njfamirm commented on ui/demo-pwa/src/director/comment-list.ts
> +commentDocumentStorageSignal.request(null);
remove

2022-12-29 07:52 UTC, njfamirm commented on ui/demo-pwa/src/director/index.ts
> +import './comment-list.js';
remove

2022-12-29 07:52 UTC, njfamirm commented on ui/demo-pwa/src/type.ts
> +};
اوکیه؟ نمیخواد توی خود المنت باشه؟

2022-12-29 11:22 UTC, njfamirm reviewed
ready for review

2022-12-31 14:18 UTC, njfamirm reviewed
ready for review

2022-12-31 17:59 UTC, AliMD commented on core/type/src/alwatr.ts
> +export const alwatrRegisteredList = globalThis.Alwatr?.registeredList || [];
اینو چرا آوردی اینجا!
الان برای درست کردنش باید ۱۰۰ جارو عوض کنم
کاش میپرسیدی

2022-12-31 18:01 UTC, njfamirm commented on core/type/src/alwatr.ts
> +export const alwatrRegisteredList = globalThis.Alwatr?.registeredList || [];
ریورت میکنم اگه نیازه

2023-01-01 08:51 UTC, njfamirm commented on core/type/src/alwatr.ts
> +export const alwatrRegisteredList = globalThis.Alwatr?.registeredList || [];
صحبت کردیم که باید بره تو پکیج manifest

2023-01-01 08:57 UTC, AliMD commented on core/type/src/service-response.ts
> +export type ParamKeyType = 'string' | 'number' | 'boolean';
این نباید اینجا باشه

2023-01-01 08:58 UTC, AliMD commented on core/type/src/service-response.ts
> +export type ParamValueType = string | number | boolean | null;
اینم همینطور

2023-01-01 10:26 UTC, AliMD requested changes

2023-01-01 10:26 UTC, AliMD commented on core/type/src/chat.ts
> +  text?: string;
؟!
چینو چرا اضافه کردی؟

2023-01-01 10:50 UTC, AliMD commented on services/storage-server/src/route/delete.ts
> +import type {AlwatrConnection} from '@alwatr/nano-server';
اینارو نباید تغییر میدادی
وقتی با یک پکیجی کار میکنی اکازه داری تایپهای مربوط به خودش رو از خودش بیاری
شما نباید بدونی که اون داره این تایپهارو از کجا میاره و اونم اجازه داره تایپهارو تغییر بده
پس استفاده کننده نهایی هر تایپ رو از پکیج خودش میاره
این موضوع در تمام سرویس ها و pwa ها باید اصلاح بشه (در پول بعدی)

2023-01-01 10:58 UTC, njfamirm commented on services/storage-server/src/route/delete.ts
> +import type {AlwatrConnection} from '@alwatr/nano-server';
اوکی

2023-01-01 11:29 UTC, AliMD approved these changes

2023-01-01 11:29 UTC, merged

2023-01-01 11:31 UTC, njfamirm commented
تبریک!