feat(type): define chat type
AliMD/alwatr pull request #592
Opened 2022-12-29 10:23 UTC by njfamirm

2022-12-29 10:33 UTC, njfamirm reviewed
ready for review

2022-12-29 11:50 UTC, AliMD commented on ui/ui-kit/src/chat/chat-message.ts
> -  type: 'text';
revert plz

2022-12-29 11:58 UTC, AliMD commented on core/type/package.json
> +  "dependencies": {
dev

2022-12-29 11:59 UTC, AliMD commented on core/type/package.json
> +    "@alwatr/storage-client": "~0.26.0"
fetch

2022-12-29 11:59 UTC, AliMD commented on core/type/tsconfig.json
> +    {"path": "../storage-client"}
!

2022-12-29 12:00 UTC, AliMD commented on services/comment/src/route/patch.ts
> +import type {Message} from '@alwatr/type/chat.js';
!

2022-12-29 12:00 UTC, AliMD commented on ui/demo-pwa/src/type.ts
> +import type {TextMessage} from '@alwatr/type/chat.js';
!

2022-12-29 12:00 UTC, AliMD commented on ui/demo-pwa/src/type.ts
> +declare global {
?!

2022-12-29 12:01 UTC, AliMD commented on ui/ui-kit/package.json
>      "tslib": "~2.4.1"
deps

2022-12-29 12:01 UTC, AliMD commented on ui/ui-kit/src/chat/chat-list.ts
> +import type {AlwatrDocumentStorage} from '@alwatr/fetch/type.js';
!

2022-12-29 12:02 UTC, AliMD commented on ui/ui-kit/src/chat/chat-message.ts
> +import type {TextMessage} from '@alwatr/type/chat.js';
!

2022-12-29 12:36 UTC, AliMD commented on ui/ui-kit/src/chat/chat-list.ts
>  export type ChatStorage = AlwatrDocumentStorage<ChatMessage>;
این چرا اینجاست؟
اینم باید بره تو تایپ

2022-12-29 12:36 UTC, AliMD requested changes
به نظرم عجله نکنیم و کامل اینو حل کن بعد مرج کنم

2022-12-29 12:40 UTC, njfamirm commented on ui/ui-kit/src/chat/chat-list.ts
>  export type ChatStorage = AlwatrDocumentStorage<ChatMessage>;
این فیکس نشده

2022-12-29 19:42 UTC, njfamirm commented on core/type/package.json
> +  "dependencies": {
کلا حدف شده توی اون یکی

2022-12-29 19:42 UTC, njfamirm commented on core/type/package.json
> +    "@alwatr/storage-client": "~0.26.0"
کلا حدف شده توی اون یکی

2022-12-29 19:42 UTC, njfamirm commented on services/comment/src/route/patch.ts
> +import type {Message} from '@alwatr/type/chat.js';
فیکس شده توی اون یکی

2022-12-29 19:42 UTC, njfamirm commented on ui/demo-pwa/src/type.ts
> +import type {TextMessage} from '@alwatr/type/chat.js';
فیکس شده توی اون یکی

2022-12-29 19:43 UTC, njfamirm commented on core/type/tsconfig.json
> +    {"path": "../storage-client"}
کلا حدف شده توی اون یکی

2022-12-29 19:43 UTC, njfamirm commented on ui/demo-pwa/src/type.ts
> +declare global {
یادم نمیاد مشکل این چی بود؟

2022-12-29 19:44 UTC, njfamirm commented on ui/ui-kit/src/chat/chat-message.ts
> +import type {TextMessage} from '@alwatr/type/chat.js';
فیکس شده توی اون یکی

2022-12-29 19:51 UTC, njfamirm commented on ui/ui-kit/src/chat/chat-list.ts
> +import type {AlwatrDocumentStorage} from '@alwatr/fetch/type.js';
مشکل چیه؟

2022-12-29 20:03 UTC, njfamirm commented
به مراااااتب خیلی بیشتر از ریویوی اون یکی پول وقت گرفت ازمون حس میکنم

2022-12-29 20:06 UTC, njfamirm commented
۱۴ تا کامیت 😭 😭

2022-12-30 03:15 UTC, njfamirm commented
اعصابمو خورد کرد
خییییلی شلوغ شد

2022-12-30 03:15 UTC, closed without merging

2022-12-30 10:08 UTC, AliMD commented
done at #600