refactor: export package uniqe types from own
AliMD/alwatr pull request #611
Opened 2023-01-02 10:04 UTC by njfamirm

2023-01-02 10:14 UTC, njfamirm commented
همه چی که بنظر درسته!
دفعه اول درست بیلد نمیشه
ولی از اون به بعد درسته

@AliMD

2023-01-04 09:57 UTC, AliMD commented on core/fetch/tsconfig.json
> +    {"path": "../nano-server"}
!

2023-01-04 09:57 UTC, AliMD commented on core/fetch/src/fetch.ts
> +} from '@alwatr/nano-server';
!

2023-01-04 09:57 UTC, AliMD commented on core/fetch/package.json
> +    "@alwatr/nano-server": "^0.27.0"
!

2023-01-04 10:00 UTC, AliMD commented on core/math/package.json
> +    "@alwatr/type": "^0.27.0"
!

2023-01-04 10:09 UTC, AliMD commented on core/storage-client/package.json
> +    "@alwatr/storage-engine": "^0.27.0"
!

2023-01-04 10:17 UTC, AliMD commented on core/storage-client/src/storage-client.ts
> +import type {AlwatrDocumentObject, AlwatrDocumentStorage} from '@alwatr/storage-engine';
!

2023-01-04 10:22 UTC, AliMD requested changes
thanks

2023-01-04 11:32 UTC, njfamirm commented
^ بشه همش دیگع؟
الان نیست

2023-01-04 15:50 UTC, mohammadhonarvar approved these changes

2023-01-05 10:25 UTC, AliMD commented on core/storage-client/src/storage-client.ts
> -export {AlwatrStorageClientConfig};
دیدیییی ریویوووو لازمهههه
ایشششششش

2023-01-05 10:48 UTC, AliMD approved these changes

2023-01-05 10:50 UTC, merged