feat(`alwatr-top-app-bar`): new components
AliMD/alwatr pull request #623
Opened 2023-01-05 15:07 UTC by MM25Zamanian

## PR Checklist

- [ ] Open an issue for bug report or feature request and mention it to this PR.
- [ ] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [ ] All methods have proper description in `jsdocs` format with `@example` section.
- [ ] Docs have been added / updated (for bug fixes / features).
- [ ] I have performed a self-review of my own code.

2023-01-13 20:51 UTC, AliMD requested changes
باهم باید بشینیم و ببندیمش...

2023-02-07 17:31 UTC, AliMD commented
@MM25Zamanian 
از پایه بازنویسی شد
ساده و جذاب شد، ببین

2023-02-07 18:06 UTC, MM25Zamanian commented
> @MM25Zamanian 
> از پایه بازنویسی شد
> ساده و جذاب شد، ببین

بله بله دیدم
برم خونه ریویو میکنم
کنجکاوم بدونم مدل های دیگه اش رو چطوری طراحی میکنین ؟

فقط ریلیز جان ما 😅

2023-02-07 19:46 UTC, MM25Zamanian reviewed
انقدر ساده شده حس میکنم نمیفهممش
نباید انقدر ساده باشه

2023-02-07 19:46 UTC, MM25Zamanian commented on ui/ui-kit/src/top-app-bar/top-app-bar.ts
> +    this.setAttribute('type', this.content.type);
به اذای هر رندر بیاد یه اتریبیوت رو ست کنه حتی وقتی ست هست
چرا ریکوعست آپدیت نه

2023-02-07 19:53 UTC, MM25Zamanian commented
عه الان دیدم
ممنونم منو از پروژه الوتر حذف نکردین

پ.ن: الان میره حذف میکنه
نکنی تورو خدا

2023-02-07 20:42 UTC, AliMD commented on ui/ui-kit/src/top-app-bar/top-app-bar.ts
> +    this.setAttribute('type', this.content.type);
یک بار بیشتر رندر نمیشه
اگر content عوض بشه طبیعتا باید دوباره رندر بشه چون ممکنه عوض شده باشه
ولی در کل حرف درستیه
پیشنهاد بهتر بده
متوجه 'ریکوعست آپدیت نه' نشدم! یعنی چی؟
ارزش داره مثلا با یک متغییر با مقدار قبلی مقایسه کنم؟

2023-02-07 20:42 UTC, AliMD commented on ui/ui-kit/src/top-app-bar/top-app-bar.ts
> +    this.setAttribute('type', this.content.type);
اینو باید ببندم
تلگرام بگو
مرسی

2023-02-07 20:52 UTC, AliMD commented on ui/ui-kit/src/top-app-bar/top-app-bar.ts
> +        line-height: calc(6 * var(--sys-spacing-track) - 0.18em); /* 0.5 * track / title-line-height */
شعار همیشگی الوتری‌ها
دقت و توجه به جزئیات 😎

2023-02-07 21:01 UTC, merged