feat(com-api): routes
AliMD/alwatr pull request #627
Opened 2023-01-07 11:10 UTC by njfamirm

2023-01-09 06:04 UTC, njfamirm commented
این تموم
ساختار توکن البته باید تایید بشه

2023-01-09 07:23 UTC, njfamirm commented
set storage new from 2nd params

2023-01-13 21:05 UTC, AliMD commented on uniquely/com-api/src/config.ts
> +  productStorage: {
داستان product چیه باز؟!
یعنی برای order میخوای یک سرسر دیگه درست کنی؟!

2023-01-13 21:06 UTC, njfamirm commented on uniquely/com-api/src/config.ts
> +  productStorage: {
الان فیکس میکنم

2023-01-13 21:07 UTC, AliMD commented on uniquely/com-api/src/route/order/get.ts
> +      data: await orderStorageClient.getStorage(),
!
data.data
میشه که

2023-01-13 21:13 UTC, AliMD requested changes
کلی نکته داره که باهم...

2023-01-13 21:13 UTC, njfamirm commented on uniquely/com-api/src/config.ts
> +  productStorage: {
اوکی

2023-01-13 21:17 UTC, njfamirm commented
این دو مورد اوکی شد

2023-01-24 10:12 UTC, njfamirm commented
بر اساس ساختار جدید اپدیت شد

2023-02-10 19:18 UTC, AliMD approved these changes

2023-02-10 19:19 UTC, merged

2023-02-10 19:22 UTC, njfamirm commented
ایولللل
واقعا خوشحالم مرج شد