feat(photo-server) : new microservice
AliMD/alwatr pull request #635
Opened 2023-01-09 19:23 UTC by njfamirm

2023-01-09 19:24 UTC, njfamirm commented
یک حس قریبی بهم میگه با توکن مشکل دارین

2023-01-13 21:24 UTC, AliMD requested changes
قرار نبود روت متا جدا داشته باشیم
روش رو قبل انجام میبندیم اینجوری دوباره کاری میشه
باهم...

2023-01-14 09:44 UTC, njfamirm commented
روت جدا حذف شد
حالا از query params میگیره

2023-01-16 09:43 UTC, njfamirm commented
پول تمیز شد
فقط یک مشکل ریز هست باید صحبت کنیم
الان بیلد نمیشه

2023-04-01 13:58 UTC, closed without merging