feat(ui-kit/image-box): new element
AliMD/alwatr pull request #721
Opened 2023-01-26 07:35 UTC by njfamirm

2023-01-26 07:36 UTC, njfamirm commented
![Uploading Screen Shot 1401-11-06 at 11.03.55.png…]()

2023-01-27 11:13 UTC, MM25Zamanian commented on ui/ui-kit/src/card/image-box.ts
> +  override render(): unknown {
یادمه یه بار @AliMD گفت که ما در نظر میگیریم بعضی چیز ها اجباری هستن و همیشه وجود دارن

پیشنهاد میکنم واسه هندل کردن این مسائل مثل فتچ یه فانکشن درست کنی که همه چی رو اونجا هندل کنی
و اینجا درگیر ولیدیشن نشی

2023-01-27 13:59 UTC, njfamirm commented on ui/ui-kit/src/card/image-box.ts
> +  override render(): unknown {
این دقیقا کد های خودشون بود که کپی کردم

2023-02-04 12:26 UTC, njfamirm commented
> داداش حس میکنم خیلی درگیری که نگاه نمیکنی ببینی برنچت آپدیت میخواد دست نزدم ولی یکم اذیت نیستی پول ریکوعست داری که بیلد نمیشه ؟؟

اولویت نداشته خب
نرفتم سراغش

2023-02-09 09:40 UTC, AliMD requested changes
این بعدا باید بازنویسی بشه فعلا فرصت نیست و مرج میکنم

2023-02-09 09:40 UTC, merged