feat(com): cdn
AliMD/alwatr pull request #983
Opened 2023-03-25 19:51 UTC by njfamirm

2023-03-25 22:27 UTC, AliMD requested changes

2023-03-25 22:27 UTC, AliMD commented on cloud/classic/com-pwa/compose.yml
> +    stop_grace_period: 30s
این برای چیه؟
مگه دیتابیسه؟!

2023-03-25 22:27 UTC, AliMD commented on cloud/classic/com-pwa/compose.yml
> +      - NGINX_ERROR_LOG_LEVEL=notice
فقط اونایی که ممکنه در cdn تغییر کنه رو بزار نه همه رو

2023-03-25 22:27 UTC, AliMD commented on cloud/classic/com-pwa/compose.yml
> +        source: ./_data/static
این اسم با اسم سرویس و prefix یکی باشه
الان که فکر میکنم cdn درست نیست

2023-03-25 22:28 UTC, AliMD commented on cloud/classic/com-pwa/compose.yml
> +        source: ./_data/static
فعلا مهم نیست ولی اگر اسم بهتری به ذهنت میرسه اونو بزار
اگر قراره این سرویس مخصوص عکس باشه پس میشه متناسب با عکس در نظر گرفت

2023-03-26 00:57 UTC, njfamirm commented
انجام شد موارد بالا

2023-03-26 09:32 UTC, njfamirm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Print button in order detail](https://trello.com/c/G43rL3gk/1-print-button-in-order-detail)

2023-03-26 10:12 UTC, njfamirm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Image CDN](https://trello.com/c/cK5pS7uC/5-image-cdn)

2023-03-27 16:23 UTC, njfamirm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Order detail print](https://trello.com/c/8PPi9M8l/2-order-detail-print)

2023-04-01 11:35 UTC, AliMD approved these changes

2023-04-01 11:35 UTC, merged